#!/bin/bash


args=$#

if [ $args -eq 0 ] ; then
	echo -e "usage: $(basename -- "$0") search_term...\nFind every user that has all of the case-insensitive unordered search\nterms present in his/her account's comment field."
else
	temp=$(getent passwd | grep $1)
	tempTwo=$temp	
	shift

	#grep "$1" <<< "$temp"


	while [ $1 ]; do
		tempTwo=$(grep "$1" <<< "$temp")
		temp=$tempTwo
		shift
	done
	

	echo $tempTwo | cut -f 1 -d ':'

fi

	
	




